### ISSUE TITLE
Interval for mqtt publishing?

### ISSUE THREAD

**Issue by RaimondB** [svrooij/smartmeter2mqtt#30]
Instead of pushing data to the mqtt endpoint each second, I would like to have a way to configure this interval.

it seems to be available for posting to a url, so maybe it is just a matter of specifying the correct configuration?

**Comment by svrooij** [comment]
Can you describe the use case of having this data less often? I've build this app to publish the information when available, and our meter is just a Dsmr4 so it will only publish every 10 seconds

**Comment by RaimondB** [comment]
My meter is publishing every second. And each minute or so would be sufficient. I can also solve it in influxdb but solving it at the source is more efficient.

**Comment by svrooij** [comment]
I understood that you didn't want the data each time it comes in, I was just wondering why you wouldn't want the most accurate data as it comes in.

Personally I use the changes in usage to trigger certain actions (frietpan is warm bericht bij afname van 1854 watt) so I have a use case to send this data as often as possible.

The beta version has support for saving it to influx, see [this issue](https://github.com/svrooij/smartmeter2mqtt/issues/19) and the attached code. In the future I probably just send all the data to influx (and mqtt) and then have some automated job in influx average out the data more then a month ago.
With a calculated usage per minute (of per configurable timespan) like max(total) - min(total) as usagePerMinute. But the attached code is just a first try of doing something with influx.

**Comment by RaimondB** [comment]
I looked a bit at the code, and wouldn't it be a matter of letting the MQTT Output inherit from IntervalOutput? Or is the interval mandatory then?
Saving it directly to influx would also reduce overhead, by using a different retention policy and a continuous query for downsampling.
https://docs.influxdata.com/influxdb/v1.8/guides/downsample_and_retain/#:~:text=Retention%20policy%28RP%29%20is%20the%20part%20of%20InfluxDB%20data,several%20RPs%20and%20RPs%20are%20unique%20per%20database.

This way you can have the most detailed data for a configurable amount of hours in the past and then change to a period you want.

Storing it directly to influx would also solve the problem, since one of the reason I want less data it that each datapoint now gets routed through my openhab setup to easily enable the influx flow that is automatically saved for all my devices. 

Is the beta version also available via docker or do I need to build this myself?

**Comment by RaimondB** [comment]
Btw the use case for the data is just to have usage statistics to compare with the power companies' statistics.
I also have use case for specific devices, but there I am using smart plugs with Z-Wave to measure usage for a specific device.
Doing it on the incoming power P1 would be to unreliable for me since it will always be a mix of a number of devices.

**Comment by svrooij** [comment]
The interval is mandatory for the interval output.

Still that doesn't explain why you don't want the latest data in mqtt.

Also influx does also saves all the data as it comes in.


Yes beta is available in docker, unless you're using a raspberry pi 3, then the current beta image will crash.  Because of a build error that has to do with multi platform builds. You can however build it yourself and use the latest image.

```shell
git clone the-correct-uri
git checkout -B beta
docker build .
```

You can see the documentation on the influx part here 
https://svrooij.io/smartmeter2mqtt/outputs/influx.html

I would just down-sample in influx (that is what's planned anyway) then everybody can decide how much downsampling to do

**Comment by RaimondB** [comment]
I am now direclty pushing to influx and downsampling where needed, thanks!
